# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10raL7OM30hNKv6-swVTL6nkGUvrG7A3T

#Task 1: Data Understanding
#• Load the dataset using Pandas
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path="/content/u_electronics_data_analysis_dataset.csv"
df=pd.read_csv(path)

"""#• Display:
* First 5 rows
* Last 5 rows
* Dataset shape
* Column names



"""

print("First 5 Rows:")
df.head(5)

print("Last 5 Rows:")
df.tail(5)

print("Dataset Shape (Rows, Columns):", df.shape)

print("--- COLUMN NAMES ---")
print(df.columns.tolist())

"""#• Identify:
* Quantitative data (Discrete & Continuous)
* Qualitative data (Nominal & Ordinal)
"""

quantitative = df.select_dtypes(include=['int64', 'float64']).columns
print("Quantitative Columns (Numerical):")
print(list(quantitative))

qualitative = df.select_dtypes(include=['object']).columns
print("\nQualitative Columns (Categorical):")
print(list(qualitative))

"""

---


#Task 2: Exploratory Data Analysis (EDA)
#Univariate Analysis
#• Analyze:
* Sales
* Profit
* Quantity

#• Use:
* Histogram
* Boxplot"""

#UNIVARIATE ANALYSIS - Final Price (Sales)


# Histogram
plt.figure(figsize=(8, 5))
sns.histplot(df["final_price"], bins=30, kde=True, color='skyblue')

plt.title("Distribution of Sales (Final Price)")
plt.xlabel("Final Price")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Boxplot
plt.figure(figsize=(8, 5))
sns.boxplot(x=df["final_price"], color='skyblue')

plt.title("Boxplot of Sales (Final Price)")
plt.xlabel("Final Price")
plt.tight_layout()
plt.show()

# UNIVARIATE ANALYSIS - Profit

# Histogram
plt.figure(figsize=(8, 5))
sns.histplot(df["Profit"], bins=30, kde=True, color='lightgreen')

plt.title("Distribution of Profit")
plt.xlabel("Profit")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Boxplot
plt.figure(figsize=(8, 5))
sns.boxplot(x=df["Profit"], color='lightgreen')

plt.title("Boxplot of Profit")
plt.xlabel("Profit")
plt.tight_layout()
plt.show()

# UNIVARIATE ANALYSIS - Stock

# Histogram
plt.figure(figsize=(8, 5))
sns.histplot(df["stock"], bins=30, kde=True, color='salmon')

plt.title("Distribution of Quantity (Stock)")
plt.xlabel("Stock")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

# Boxplot
plt.figure(figsize=(8, 5))
sns.boxplot(x=df["stock"], color='salmon')

plt.title("Boxplot of Quantity (Stock)")
plt.xlabel("Stock")
plt.tight_layout()
plt.show()

"""#Bivariate Analysis

#• Analyze:
* Sales vs Profit
* Discount vs Profit
* Quantity vs Sales
#• Use:
* Scatter plots
* Correlation matrix
"""

plt.figure(figsize=(8, 5))

sns.scatterplot(x=df["final_price"], y=df["Profit"], color='skyblue', alpha=0.6)

plt.title("Sales (Final Price) vs Profit")
plt.xlabel("Final Price (Sales)")
plt.ylabel("Profit")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))

sns.scatterplot(x=df["discount_percent"], y=df["Profit"], color='salmon', alpha=0.6)

plt.title("Discount Percent vs Profit")
plt.xlabel("Discount Percent")
plt.ylabel("Profit")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))

sns.scatterplot(x=df["stock"], y=df["final_price"], color='lightgreen', alpha=0.6)

plt.title("Quantity (Stock) vs Sales (Final Price)")
plt.xlabel("Stock (Quantity)")
plt.ylabel("Final Price (Sales)")
plt.tight_layout()
plt.show()

# CORRELATION MATRIX

numeric_cols = ['price', 'discount_percent', 'final_price', 'rating', 'stock', 'Profit', 'Loss']

corr_matrix = df[numeric_cols].corr()
print("Correlation Matrix:")
print(corr_matrix)

plt.figure(figsize=(10, 7))

sns.heatmap(corr_matrix,
            annot=True,
            fmt=".2f",
            cmap="coolwarm",
            vmin=-1, vmax=1,
            linewidths=0.5,
            square=True)

plt.title("Correlation Matrix - Electronics Dataset")
plt.tight_layout()
plt.show()

"""#Multivariate Analysis
#• Analyze:
* Sales, Profit, Discount across Categories
#• Use:
* Pair plots
* Heatmap
"""

sns.pairplot(df[["price", "final_price", "discount_percent", "Profit", "stock"]],
             diag_kind='kde',
             plot_kws={'alpha': 0.5})

plt.suptitle("Pair Plot - Multivariate Analysis", y=1.02)
plt.show()

category_data = df.groupby('category')[['final_price', 'Profit', 'discount_percent']].mean()

plt.figure(figsize=(10, 6))

sns.heatmap(category_data,
            annot=True,
            fmt=".1f",
            cmap="coolwarm",
            linewidths=0.5,
            square=False)

plt.title("Avg Sales, Profit & Discount Across Categories")
plt.tight_layout()
plt.show()

"""

---


#Task 3: Handling Missing Data and Outliers
#• Identify missing values"""

print("Missing Values in Each Column:")
df.isnull().sum()

"""#• Handle missing values using:
* Mean / Median / Mode
"""

# Continuous columns → Median (bcz of outliers)
median_cols = ['price', 'final_price', 'discount_percent', 'rating']
for col in median_cols:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)
    print(f"{col} → filled with Median: {median_val}")

# Discrete columns → Mean
mean_cols = ['stock', 'Profit', 'Loss']
for col in mean_cols:
    mean_val = round(df[col].mean())
    df[col].fillna(mean_val, inplace=True)
    print(f"{col} → filled with Mean: {mean_val}")

# Categorical columns → Mode
cat_cols = ['category', 'brand']
for col in cat_cols:
    mode_val = df[col].mode()[0]
    df[col].fillna(mode_val, inplace=True)
    print(f"{col} → filled with Mode: {mode_val}")

# Verify
print("\n=== AFTER FILLING - MISSING VALUES ===")
print(df.isnull().sum())

"""#• Detect outliers using:
* Boxplots
"""

# Detect Outliers using Boxplot

cols_to_check = ['price', 'final_price', 'Profit', 'stock']

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
axes = axes.flatten()

colors = ['skyblue', 'lightgreen', 'salmon', 'plum']

for i, col in enumerate(cols_to_check):
    sns.boxplot(y=df[col], ax=axes[i], color=colors[i])
    axes[i].set_title(f'Boxplot - {col}')
    axes[i].set_ylabel(col)

plt.suptitle("Outlier Detection using Boxplots", fontsize=14)
plt.tight_layout()
plt.show()

# Count Outliers using IQR Method

print("=== OUTLIER COUNT PER COLUMN ===")
for col in cols_to_check:
    Q1  = df[col].quantile(0.25)
    Q3  = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"{col:15} → Outliers: {len(outliers)}  |  Lower: {lower:.1f}  |  Upper: {upper:.1f}")

"""#• Explain the impact of outliers"""

# Impact of Outliers - Explain with Example

print("=== IMPACT OF OUTLIERS ON PROFIT ===")
print(f"Mean   WITH outliers  : {df['Profit'].mean():.2f}")
print(f"Median WITH outliers  : {df['Profit'].median():.2f}")

# Outliers remove
Q1  = df['Profit'].quantile(0.25)
Q3  = df['Profit'].quantile(0.75)
IQR = Q3 - Q1
clean = df[(df['Profit'] >= Q1 - 1.5*IQR) & (df['Profit'] <= Q3 + 1.5*IQR)]

print(f"\nMean   WITHOUT outliers: {clean['Profit'].mean():.2f}")
print(f"Median WITHOUT outliers: {clean['Profit'].median():.2f}")
print(f"\nMean difference  : {abs(df['Profit'].mean() - clean['Profit'].mean()):.2f}")
print(f"Median difference: {abs(df['Profit'].median() - clean['Profit'].median()):.2f}")
print("\n→ Mean zyada affect hua — outliers mean ko bigadte hain!")
print("→ Median almost same raha — median outliers se safe hai!")

"""---


#Task 4: Spread of Data

#• Check data distribution:
* Normal distribution
* Skewed distribution

#• Calculate:
* Mean
* Median
* Standard deviation
* Skewness
* Kurtosis
"""

# Calculate Mean, Median, Std, Skewness, Kurtosis


cols = ['price', 'final_price', 'discount_percent', 'Profit', 'stock']

print("=" * 65)
print(f"{'Column':<18} {'Mean':>8} {'Median':>8} {'Std':>8} {'Skew':>8} {'Kurt':>8}")
print("=" * 65)

for col in cols:
    mean   = df[col].mean()
    median = df[col].median()
    std    = df[col].std()
    skew   = df[col].skew()
    kurt   = df[col].kurtosis()
    print(f"{col:<18} {mean:>8.1f} {median:>8.1f} {std:>8.1f} {skew:>8.2f} {kurt:>8.2f}")

print("=" * 65)

# Distribution Plots - Normal vs Skewed check

fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()

colors = ['skyblue', 'lightgreen', 'salmon', 'plum', 'orange']

for i, col in enumerate(cols):
    sns.histplot(df[col], bins=30, kde=True,
                 color=colors[i], ax=axes[i])

    # Mean aur Median lines
    axes[i].axvline(df[col].mean(),   color='red',  linestyle='--', label='Mean')
    axes[i].axvline(df[col].median(), color='blue', linestyle='--', label='Median')

    axes[i].set_title(f'{col} | Skew={df[col].skew():.2f}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frequency')
    axes[i].legend()

axes[5].set_visible(False)  # 6th cell empty hai

plt.suptitle("Data Distribution - Normal vs Skewed", fontsize=14)
plt.tight_layout()
plt.show()

"""# • Interpret results"""

# Interpret Results

print("\n=== SKEWNESS INTERPRETATION ===")
for col in cols:
    skew = df[col].skew()
    if skew > 0.5:
        result = "Right Skewed (tail right mein)"
    elif skew < -0.5:
        result = "Left Skewed (tail left mein)"
    else:
        result = "Normal Distribution"
    print(f"{col:<20} skew={skew:>6.2f}  →  {result}")

"""

---


#Task 5: Automating EDA using Python
#• Use Pandas and NumPy functions:
* describe()
* info()
* isnull()
* corr()"""

print("=== df.describe() ===")
print(df.describe())

print("=== df.info() ===")
df.info()

print("=== df.isnull().sum() ===")
print(df.isnull().sum())

print("=== df.corr() ===")
print(df[['price','discount_percent','final_price','Profit','stock']].corr())

"""# • Write reusable Python functions for EDA"""

def perform_eda(dataframe):

    print("=" * 60)
    print("1. SHAPE")
    print("=" * 60)
    print(f"Rows: {dataframe.shape[0]}, Columns: {dataframe.shape[1]}")

    print("\n" + "=" * 60)
    print("2. DATA TYPES")
    print("=" * 60)
    print(dataframe.dtypes)

    print("\n" + "=" * 60)
    print("3. MISSING VALUES")
    print("=" * 60)
    print(dataframe.isnull().sum())

    print("\n" + "=" * 60)
    print("4. STATISTICAL SUMMARY")
    print("=" * 60)
    print(dataframe.describe())

    print("\n" + "=" * 60)
    print("5. SKEWNESS")
    print("=" * 60)
    print(dataframe.skew(numeric_only=True))

    print("\n" + "=" * 60)
    print("6. CORRELATION MATRIX")
    print("=" * 60)
    print(dataframe.corr(numeric_only=True))

    print("\nEDA Complete!")

perform_eda(df)

"""

---


# Task 6: Regression Analysis
#• Identify:
* Dependent variable (Sales)
* Independent variables (Quantity, Discount)"""

X = df[["stock", "discount_percent"]]   # Independent variables
y = df["final_price"]                   # Dependent variable (Sales)

"""#• Analyze:
- Covariance
- Correlation
"""

# Covariance


cols = ['price', 'discount_percent', 'final_price', 'Profit', 'stock']

print("=== COVARIANCE MATRIX ===")
cov_matrix = df[cols].cov()
print(cov_matrix)

# Covariance Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(cov_matrix,
            annot=True,
            fmt=".0f",
            cmap="coolwarm",
            linewidths=0.5)

plt.title("Covariance Matrix - Heatmap")
plt.tight_layout()
plt.show()

# Correlation


print("=== CORRELATION MATRIX ===")
corr_matrix = df[cols].corr()
print(corr_matrix)

# Correlation Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(corr_matrix,
            annot=True,
            fmt=".2f",
            cmap="coolwarm",
            vmin=-1, vmax=1,
            linewidths=0.5,
            square=True)

plt.title("Correlation Matrix - Heatmap")
plt.tight_layout()
plt.show()

"""# Perform:
* Simple Linear Regression
"""

from sklearn.linear_model import LinearRegression

X = df[["stock"]]   # Independent variable
y = df["final_price"]  # Dependent variable

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

plt.figure(figsize=(8,5))

plt.scatter(df["stock"], df["final_price"], color="skyblue", label="Actual Data")

plt.plot(df["stock"], y_pred, color="red", label="Regression Line")

plt.xlabel("Stock (Quantity)")
plt.ylabel("Sales (Final Price)")
plt.title("Simple Linear Regression: Stock vs Sales")

plt.legend()

plt.show()

"""

---


#Task 7: Supervised Learning – Regression Model
#• Split dataset into:
* Training data
* Testing data"""

from sklearn.model_selection import train_test_split

X = df[["stock", "discount_percent"]]   # Independent variables
y = df["final_price"]                   # Dependent variable

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""#• Build regression model using:
* LinearRegression (sklearn)
"""

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

"""# Make Predictions


"""

y_pred = model.predict(X_test)

"""# Result

#Overfitting:
Overfitting occurs when a model performs very well on training data but poorly on testing data because it has learned noise and specific details instead of general patterns.

#Underfitting:
Underfitting occurs when a model is too simple and fails to capture the relationship between variables, resulting in poor performance on both training and testing data.
"""

print("--- Task 7 Results ---")
print(f"Total Data points: {len(df)}")
print(f"Training points: {len(X_train)}")
print(f"Testing points: {len(X_test)}")

# Check for Overfitting and Underfitting
train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

print(f"\nTraining Accuracy (R2): {train_score:.4f}")
print(f"Testing Accuracy (R2): {test_score:.4f}")

# Overfitting/Underfitting Interpretation [cite: 137]
if train_score > test_score + 0.1:
    print("Observation: Model Overfit (Good at Training, Bad at Testing).")
elif train_score < 0.5 and test_score < 0.5:
    print("Observation: Model Underfit (Bad at both).")
else:
    print("Observation: Model balanced hai.")

"""# Simple Linear Regression Model"""

X_simple = df[["stock"]]
y_simple = df["final_price"]

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_simple, y_simple, test_size=0.2, random_state=42
)

simple_model = LinearRegression()

simple_model.fit(X_train_s, y_train_s)

"""# Multiple Linear Regression Model"""

X_multi = df[["stock", "discount_percent"]]
y_multi = df["final_price"]

multi_model = LinearRegression()

multi_model.fit(X_train, y_train)

"""---

#Task 9: Overfitting and Underfitting Analysis
#• Explain concepts of overfitting and underfitting

#• Compare training and testing errors
"""

from sklearn.metrics import mean_squared_error

# Predictions
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

# Errors
train_error = mean_squared_error(y_train, train_pred)
test_error = mean_squared_error(y_test, test_pred)

print("Training Error:", train_error)
print("Testing Error:", test_error)

"""#• Demonstrate how model complexity affects performance"""

plt.figure(figsize=(8,5))

# Actual values (blue)
plt.scatter(y_test, y_test, color="blue", label="Actual")

# Predicted values (red)
plt.scatter(y_test, test_pred, color="red", label="Predicted")

plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")

plt.title("Actual vs Predicted Sales")

plt.legend()

plt.show()

"""

---

#Task 10: Classification Task
#• Convert the problem into a classification problem
* (Example: Profit → Profitable / Not Profitable)"""

# CLASSIFICATION TASK

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Make  Profit binary
df['Profitable'] = (df['Profit'] > 0).astype(int)
print(df['Profitable'].value_counts())

"""# • Build a classification model using supervised learning"""

from sklearn.linear_model import LogisticRegression

X = df[['final_price', 'discount_percent', 'stock']]
y = df['Profitable']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

log_clf = LogisticRegression(max_iter=1000)
log_clf.fit(X_train, y_train)
y_pred = log_clf.predict(X_test)

print("=== CLASSIFICATION REPORT ===")
print(classification_report(y_test, y_pred,
      target_names=['Not Profitable', 'Profitable']))

"""# • Evaluate classification performance using:
* Accuracy
* Confusion Matrix
"""

# Confusion Matrix
plt.figure(figsize=(6, 4))
sns.heatmap(confusion_matrix(y_test, y_pred),
            annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Profitable', 'Profitable'],
            yticklabels=['Not Profitable', 'Profitable'])
plt.title("Confusion Matrix - Classification")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()

"""

---

# Task 11: Model Evaluation
# • Calculate and interpret:
* Mean Squared Error (MSE)
* Mean Absolute Error (MAE)
* R² Score (for regression)"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, test_pred)
print("Mean Squared Error:", mse)

mae = mean_absolute_error(y_test, test_pred)
print("Mean Absolute Error:", mae)

r2 = r2_score(y_test, test_pred)
print("R2 Score:", r2)

"""

---


# Task 13: Data visualization
# • Plots:
* Univariate analysis plots  """

# Univariate Plots
fig, axes = plt.subplots(2, 3, figsize=(15, 8))
axes = axes.flatten()
cols = ['price', 'final_price', 'discount_percent', 'Profit', 'stock']
colors = ['plum', 'skyblue', 'orange', 'lightgreen', 'salmon']

for i, col in enumerate(cols):
    sns.histplot(df[col], bins=30, kde=True, color=colors[i], ax=axes[i])
    axes[i].set_title(f'Univariate - {col}')
    axes[i].set_xlabel(col)

axes[5].set_visible(False)
plt.suptitle("Task 13 - Univariate Analysis Plots", fontsize=14)
plt.tight_layout()
plt.show()

"""* Bi-variate analysis plots"""

# Bivariate Plots
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

sns.scatterplot(x=df['final_price'], y=df['Profit'],
                alpha=0.5, color='skyblue', ax=axes[0])
axes[0].set_title("final_price vs Profit")

sns.scatterplot(x=df['discount_percent'], y=df['Profit'],
                alpha=0.5, color='salmon', ax=axes[1])
axes[1].set_title("discount_percent vs Profit")

sns.scatterplot(x=df['stock'], y=df['final_price'],
                alpha=0.5, color='lightgreen', ax=axes[2])
axes[2].set_title("stock vs final_price")

plt.suptitle("Task 13 - Bivariate Analysis Plots", fontsize=14)
plt.tight_layout()
plt.show()

"""* Multi-variate analysis plots"""

# Multivariate Plot
cols = ['price', 'final_price', 'discount_percent', 'Profit', 'stock']
sns.pairplot(df[cols], diag_kind='kde', plot_kws={'alpha': 0.5})
plt.suptitle("Task 13 - Multivariate Analysis (Pair Plot)", y=1.02)
plt.show()

# CORRELATION MATRIX

numeric_cols = ['price', 'discount_percent', 'final_price', 'rating', 'stock', 'Profit', 'Loss']

corr_matrix = df[numeric_cols].corr()
print("Correlation Matrix:")
print(corr_matrix)

plt.figure(figsize=(10, 7))

sns.heatmap(corr_matrix,
            annot=True,
            fmt=".2f",
            cmap="coolwarm",
            vmin=-1, vmax=1,
            linewidths=0.5,
            square=True)

plt.title("Correlation Matrix - Electronics Dataset")
plt.tight_layout()
plt.show()

"""# • Data normalization plots (Normal distribution, skewness)"""

# Data Normalization Plot - Skewness
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.histplot(df['Profit'], bins=30, kde=True, color='lightgreen', ax=axes[0])
axes[0].set_title(f"Profit - Right Skewed (skew={df['Profit'].skew():.2f})")
axes[0].axvline(df['Profit'].mean(),   color='red',  linestyle='--', label='Mean')
axes[0].axvline(df['Profit'].median(), color='blue', linestyle='--', label='Median')
axes[0].legend()

sns.histplot(df['stock'], bins=30, kde=True, color='salmon', ax=axes[1])
axes[1].set_title(f"Stock - Normal (skew={df['stock'].skew():.2f})")
axes[1].axvline(df['stock'].mean(),   color='red',  linestyle='--', label='Mean')
axes[1].axvline(df['stock'].median(), color='blue', linestyle='--', label='Median')
axes[1].legend()

plt.suptitle("Task 13 - Normal vs Skewed Distribution", fontsize=14)
plt.tight_layout()
plt.show()